import 'package:flutter/material.dart';
import 'package:pet_adoption_app/src/presentation/config/themes/color_palette.dart';
import 'package:pet_adoption_app/src/presentation/config/themes/dark_theme.dart';
import 'package:pet_adoption_app/src/presentation/config/themes/light_theme.dart';
import 'package:pet_adoption_app/src/presentation/config/themes/text_theme.dart';

class AppTheme {
  static ThemeData get light => ThemeData(
    brightness: Brightness.light,
    primaryColor: LightTheme.primaryColor,
    primaryColorDark: LightTheme.primaryColorDark,
    primaryColorLight: LightTheme.primaryColorLight,
    scaffoldBackgroundColor: LightTheme.backgroundColor,
    cardColor: LightTheme.cardBackgroundColor,
    disabledColor: ColorPalette.greyLighten3,
    colorScheme: const ColorScheme.light(
      primary: LightTheme.primaryColor,
      onPrimary: LightTheme.onPrimaryColor,
      primaryContainer: LightTheme.primaryColorLight,
      onPrimaryContainer: LightTheme.primaryColor,
      primaryFixed: LightTheme.primaryColorFixed,
      onPrimaryFixed: LightTheme.onPrimaryColor,
      primaryFixedDim: LightTheme.primaryColorDim,
      onPrimaryFixedVariant: LightTheme.onPrimaryColor,
      inversePrimary: LightTheme.inversePrimaryColor,
      secondary: LightTheme.secondaryColor,
      onSecondary: LightTheme.onSecondaryColor,
      secondaryContainer: LightTheme.secondaryColorLight,
      onSecondaryContainer: LightTheme.secondaryColor,
      secondaryFixed: LightTheme.secondaryColorFixed,
      onSecondaryFixed: LightTheme.onSecondaryColor,
      secondaryFixedDim: LightTheme.secondaryColorDim,
      onSecondaryFixedVariant: LightTheme.onSecondaryColor,
      tertiary: LightTheme.tertiaryColor,
      onTertiary: LightTheme.onTertiaryColor,
      tertiaryContainer: LightTheme.tertiaryColorLight,
      onTertiaryContainer: LightTheme.tertiaryColor,
      tertiaryFixed: LightTheme.tertiaryColorFixed,
      onTertiaryFixed: LightTheme.onTertiaryColor,
      tertiaryFixedDim: LightTheme.tertiaryColorDim,
      onTertiaryFixedVariant: LightTheme.onTertiaryColor,
      surface: LightTheme.cardBackgroundColor,
      onSurface: ColorPalette.greyDarken3,
      outline: ColorPalette.greyLighten2,
      outlineVariant: ColorPalette.greyLighten2,
      shadow: ColorPalette.greyDarken4,
      error: ColorPalette.error,
      onError: LightTheme.onPrimaryColor,
    ),
    appBarTheme: const AppBarTheme(
      backgroundColor: LightTheme.cardBackgroundColor,
      foregroundColor: ColorPalette.greyDarken3,
      centerTitle: true,
    ),
    // tabBarTheme: const TabBarTheme(
    //   labelColor: LightTheme.primaryColor,
    //   indicatorColor: LightTheme.primaryColor,
    //   unselectedLabelColor: ColorPalette.greyDarken3,
    //   indicatorSize: TabBarIndicatorSize.label,
    //   dividerHeight: 0,
    //   dividerColor: Colors.transparent,
    //   labelStyle: TextStyle(
    //     fontWeight: FontWeight.w600,
    //   ),
    // ),
    floatingActionButtonTheme: const FloatingActionButtonThemeData(
      backgroundColor: LightTheme.primaryColor,
      foregroundColor: LightTheme.onPrimaryColor,
    ),
    textTheme: AppTextTheme.light,
  );

  static ThemeData get dark => ThemeData(
    brightness: Brightness.dark,
    primaryColor: DarkTheme.primaryColor,
    primaryColorDark: DarkTheme.primaryColorDark,
    primaryColorLight: DarkTheme.primaryColorLight,
    scaffoldBackgroundColor: DarkTheme.backgroundColor,
    cardColor: DarkTheme.cardBackgroundColor,
    disabledColor: ColorPalette.greyDarken3,
    colorScheme: const ColorScheme.dark(
      primary: DarkTheme.primaryColor,
      primaryContainer: DarkTheme.primaryColorLight,
      onPrimary: DarkTheme.onPrimaryColor,
      secondary: DarkTheme.secondaryColor,
      secondaryContainer: DarkTheme.secondaryColorLight,
      onSecondary: DarkTheme.onSecondaryColor,
      tertiary: DarkTheme.tertiaryColor,
      tertiaryContainer: DarkTheme.tertiaryColorLight,
      onTertiary: DarkTheme.onTertiaryColor,
      surface: DarkTheme.cardBackgroundColor,
      onSurface: ColorPalette.greyLighten4,
      outline: ColorPalette.greyDarken3,
      outlineVariant: ColorPalette.greyDarken2,
      shadow: ColorPalette.greyDarken1,
      error: ColorPalette.error,
      onError: DarkTheme.onPrimaryColor,
    ),
    appBarTheme: const AppBarTheme(
      backgroundColor: DarkTheme.cardBackgroundColor,
      foregroundColor: ColorPalette.greyLighten4,
      centerTitle: true,
    ),
    // tabBarTheme: const TabBarTheme(
    //   labelColor: DarkTheme.primaryColor,
    //   indicatorColor: DarkTheme.primaryColor,
    //   unselectedLabelColor: DarkTheme.secondaryTextColor,
    //   indicatorSize: TabBarIndicatorSize.label,
    //   dividerHeight: 0.5,
    //   dividerColor: ColorPalette.greyDarken3,
    // ),
    floatingActionButtonTheme: const FloatingActionButtonThemeData(
      backgroundColor: LightTheme.primaryColor,
      foregroundColor: LightTheme.onPrimaryColor,
    ),
    textTheme: AppTextTheme.dark,
  );
}
